### ISSUE TITLE
你好，这个空指针怎么解决，在fragment里面加入  .compose(RxLife.with(this).bindToLifecycle())

### ISSUE THREAD

**Issue by huangxumin** [dhhAndroid/RxLife#3]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.reactivex.subjects.Subject.onNext(java.lang.Object)' on a null object reference
        at com.dhh.rxlife2.LifecycleBridge.onStateChanged(LifecycleBridge.kt:29)
        at com.dhh.rxlife2.LifecycleBridgeBase.onStateChanged(LifecycleBridgeBase.kt:31)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:355)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:181)
        at com.dhh.rxlife2.LifecycleBridgeBase.<init>(LifecycleBridgeBase.kt:21)
        at com.dhh.rxlife2.LifecycleBridge.<init>(LifecycleBridge.kt:14)
        at com.dhh.rxlife2.LifecycleBridge$Companion.get(LifecycleBridge.kt:19)
        at com.dhh.rxlife2.RxLife.with(RxLife.kt:17)
        at com.yunniu.isonic_smarthome.ui.fragment.MyHouseFragments.initView(MyHouseFragments.java:374)
        at com.yunniu.isonic_smarthome.ui.fragment.MyHouseFragments.onCreateView(MyHouseFragments.java:145)

**Comment by huangxumin** [comment]
额，我现在oncreate调用 RxLife.with(this)，初始化之后就不会出现这个问题了。。

**Comment by huangxumin** [comment]
Attempt to invoke virtual method 'void io.reactivex.subjects.Subject.onNext(java.lang.Object)' on a null object reference，其他地方还是会报错。

**Comment by dhh-io** [comment]
你调用代码我看一下，是否添加依赖 RxJava2，我看了代码，此处调用的是  lifecycleSubject.onNext()方法，lifecycleSubject已经在类实例化的时候初始化了 lifecycleSubject，[点击查看LifecycleBridge代码](https://github.com/dhhAndroid/RxLife/blob/6e10ce298e314acbf108fda91518a38691b53283/rxLife2/src/main/java/com/dhh/rxlife2/LifecycleBridge.kt#L29)，另外在Activity里使用有问题吗 ？是不是Fragment 的问题，Fragment只能是v4包下的 Fragment

**Comment by dhh-io** [comment]
@huangxumin Fragment应该是动态添加的吧 ？

**Comment by huangxumin** [comment]
有添加rxjava2依赖，activity也会出现这个问题，我觉得不是fragment的问题。我跳转activity也会出现这个问题。fargment是动态添加的   

     //判断此Fragment是否已经添加到FragmentTransaction事物中
        if (!fragment.isAdded()) {
            ft.add(R.id.fragment, fragment, fragment.getClass().getName());
        } else {
            ft.show(fragment);
        }

是v4的fragment,activity继承fragmentAvtivity.

这是activity和fragmrnt的调用代码：
注释的rxlife,我现在用RxLifecycle测试。

baseActivity里面：

    public <T> LifecycleTransformer<T> bindToLifecycle() {
//        return RxLife.with(this).bindOnDestroy();
        return RxLifecycle.with(this).bindOnDestroy();
    }
调用：

    RxView.clicks(back).throttleFirst(1, TimeUnit.SECONDS).compose(bindToLifecycle())
.subscribe(new Consumer<Unit>() {
            @Override
            public void accept(Unit o) throws Exception {
                onBackPressed();
            }
        });

**Comment by dhh-io** [comment]
原因我已经查到，类加载构造方法执行顺序的问题，可能会导致这个问题，我正在解决，随后发布代码

**Comment by dhh-io** [comment]
你试一下使用最新的1.1.3版本，能否解决问题
